In [1]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D, Conv2DTranspose, Dense
from tensorflow.keras.preprocessing import image_dataset_from_directory

In [2]:
input_shape = (1, 28, 28, 1)
x = tf.random.normal(input_shape)
y = Conv2D(filters=1, kernel_size=(3, 3), strides=2)(x)
print(y.shape)
print(Conv2D(filters=1, kernel_size=(5, 5), strides=2)(x).shape)
x1 = Conv2D(filters=1, kernel_size=(3, 1), strides=1)(x)
x2 = Conv2D(filters=1, kernel_size=(1, 3), strides=2)(x1)
print(x1.shape)
print(x2.shape)

(1, 13, 13, 1)
(1, 12, 12, 1)
(1, 26, 28, 1)
(1, 13, 13, 1)


In [27]:
x = tf.random.normal((1, 7, 7, 1))
x1 = Conv2DTranspose(filters=1, kernel_size=(3, 3), strides=2, padding="same")(x)
print(x1.shape)

(1, 14, 14, 1)


In [8]:
g_d = image_dataset_from_directory('./data/test_set/',
                                    batch_size=2,
                                    image_size=(64, 64))
a = g_d.as_numpy_iterator().next()[0]
print((a.astype('float32') - 127.5) / 127.5)

Found 2023 files belonging to 2 classes.
[[[[-0.29767156 -0.266299   -0.24276961]
   [-0.28111595 -0.24974342 -0.226214  ]
   [-0.21294424 -0.19897366 -0.15961626]
   ...
   [-0.07741269 -0.18010876 -0.12447151]
   [-0.12301624 -0.25291818 -0.19188878]
   [-0.13811274 -0.26213235 -0.20404412]]

  [[-0.1322189  -0.10084636 -0.07731694]
   [ 0.02374004  0.05511259  0.078642  ]
   [-0.01556373  0.04135646  0.0823606 ]
   ...
   [ 0.12172181  0.03930377  0.06462163]
   [ 0.03581878 -0.05486749 -0.04089691]
   [ 0.03453584 -0.0865311  -0.06300168]]

  [[ 0.44440106  0.47320005  0.49587163]
   [ 0.62040824  0.64920723  0.6718788 ]
   [ 0.7327206   0.7384115   0.7002719 ]
   ...
   [ 0.38977483  0.3487477   0.32869178]
   [ 0.35065487  0.28705192  0.2739392 ]
   [ 0.31232     0.2566636   0.24173178]]

  ...

  [[ 0.6737745   0.6580882   0.5561274 ]
   [ 0.67897904  0.66329277  0.5613319 ]
   [ 0.80364585  0.7482537   0.68619025]
   ...
   [-0.31715685 -0.6142157  -0.6392157 ]
   [-0.288691   

In [38]:

fake = tf.random.uniform([2, 2, 2, 1])

real = tf.random.uniform([2, 2, 2, 1])

a = tf.random.uniform([2, 1, 1, 1], 0., 1.)
print(a)

diff = fake - real
inter = real + a * diff
print(diff)
print(a * diff)
# fw = Dense(5)
# d = Dense(1)


# with tf.GradientTape() as tape:
#     tape.watch(inter)
#     g = d(fw(inter))
#     print(tf.matmul(fw.get_weights()[0], d.get_weights()[0]))
# grad = tape.gradient(g, [inter])
# print(grad)
# print(grad[0])



tf.Tensor(
[[[[0.439803  ]]]


 [[[0.23563206]]]], shape=(2, 1, 1, 1), dtype=float32)
tf.Tensor(
[[[[ 0.7490442 ]
   [ 0.14348364]]

  [[ 0.6117774 ]
   [ 0.01831901]]]


 [[[ 0.1613574 ]
   [ 0.69692254]]

  [[-0.46455336]
   [ 0.40712082]]]], shape=(2, 2, 2, 1), dtype=float32)
tf.Tensor(
[[[[ 0.3294319 ]
   [ 0.06310453]]

  [[ 0.26906154]
   [ 0.00805676]]]


 [[[ 0.03802098]
   [ 0.1642173 ]]

  [[-0.10946366]
   [ 0.09593072]]]], shape=(2, 2, 2, 1), dtype=float32)
